### Linear Algebra Refresher

- **Vector operations**
- **Multiplication**
    - Vector-vector multiplication
    - Matrix-vector multiplication
    - Matrix-matrix multiplication
- **Identity matrix**
- **Inverse**

**Vector operations**

In [2]:
import numpy as np 
import pandas as pd

In [19]:
u = np.array([1,2,3,4])
v = np.array([6,7,8,9])

print('u',u)
print('v',v)
print('\n sum', u+v)
print('\n multiply', u*v)
print('\n subtract', u-v)
print('\n scalar multipication', u*3)

u [1 2 3 4]
v [6 7 8 9]

 sum [ 7  9 11 13]

 multiply [ 6 14 24 36]

 subtract [-5 -5 -5 -5]

 scalar multipication [ 3  6  9 12]


**Dot product**

In [22]:
a = np.array([2,2,2])
b = np.array([3,3,3])

a.dot(b)

18

In [32]:
a = np.array([2,2,2])
b = np.array([3,3,3])

def vector_multiply(a, b):
    # Check if the shapes are compatible
    assert a.shape[0] == b.shape[0]

    # Initialize the product accumulator
    product = 0

    # Perform element-wise multiplication and accumulation
    for i in range(len(a)):
        product = product + a[i] * b[i]
    return product

vector_multiply(a, b)



18

**Matrix multipication**

In [78]:
import numpy as np

s = np.array([[2, 2, 2], [3, 3, 3]])
v = np.array([[4, 4], [5, 5], [6, 6]])

print("Matrix s:")
print(s)
print("\nMatrix v:")
print(v)

def matrix_multiply(s, v):
    # Check if the number of columns in s matches the number of rows in v
    assert s.shape[1] == v.shape[0], "Number of columns in s must match the number of rows in v for matrix multiplication"
    
    # Initialize the result matrix with zeros
    result = np.zeros((s.shape[0], v.shape[1]))

    # Perform matrix multiplication
    for i in range(s.shape[0]):  # Iterate over rows of s
        for j in range(v.shape[1]):  # Iterate over columns of v
            sum = 0
            for k in range(s.shape[1]):  # Dot product of row i of s and column j of v
                sum += s[i, k] * v[k, j]
            result[i, j] = sum

    print("\n Result of matrix multiplication:")
    return result

# Call the function
matrix_multiply(s, v)


Matrix s:
[[2 2 2]
 [3 3 3]]

Matrix v:
[[4 4]
 [5 5]
 [6 6]]

 Result of matrix multiplication:


array([[30., 30.],
       [45., 45.]])

**Identity matrix**

In [79]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

**Inverse matrix**

In [95]:
j = np.array([[1,2,3],[45,65,78],[33,54,67]])

print('j \n',j)

j_inv = np.linalg.inv(j)
print('\n j_inv \n', j_inv)
matrix = np.dot(j,j_inv)

print('\n j_inv * j\n', np.round(matrix,2))

j 
 [[ 1  2  3]
 [45 65 78]
 [33 54 67]]

 j_inv 
 [[ 1.23275862  0.24137931 -0.3362069 ]
 [-3.80172414 -0.27586207  0.49137931]
 [ 2.45689655  0.10344828 -0.21551724]]

 j_inv * j
 [[ 1. -0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]
