In [1]:
import numpy as np 

#### Creating Arrays with Zeros, Ones, or Constants


In [2]:

np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### Converting Lists to Arrays

In [10]:
l1 = [1,2,3,7,27]

c = np.array(l1)
c

array([ 1,  2,  3,  7, 27])

#### ranges

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

#### Multi-dimensional array

In [14]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
# constant matrix 
np.full((3, 6), 2)

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

#### Indexing and Slicing Arrays

In [38]:
arr =  np.array([[2, 3, 4], [5, 6, 7]])
print(arr)
print(arr[0])
print(arr[0,1])
print(arr[1,2])

print('\n first column')
print(arr[:,0])

print('\n first row')
print(arr[0,:])

[[2 3 4]
 [5 6 7]]
[2 3 4]
3
7

 first column
[2 5]

 first row
[2 3 4]


#### Generating Random Arrays


In [40]:
np.random.seed(43)
np.random.rand(5,2)

array([[0.11505457, 0.60906654],
       [0.13339096, 0.24058962],
       [0.32713906, 0.85913749],
       [0.66609021, 0.54116221],
       [0.02901382, 0.7337483 ]])

In [43]:
np.random.randint(low = 2, high= 100 ,size= (2,6))

array([[36, 77, 68,  6, 38, 78],
       [90, 49, 34, 76, 62, 75]])

#### Array Operations

In [56]:
arr1 = np.array([1,2,34])
arr1 * 2

array([ 2,  4, 68])

In [58]:
arr2 = np.array([2,1,3])
arr1 + arr2

array([ 3,  3, 37])

In [59]:
arr1/arr2 + 2

array([ 2.5       ,  4.        , 13.33333333])

In [62]:
arr3 = arr1 + 5
arr3

array([ 6,  7, 39])

In [63]:
arr3>30

array([False, False,  True])

#### Selecting Elements Based on Conditions

In [64]:
arr[arr>30]

array([34])

#### Summary Operations

In [72]:
arr = np.random.randint(low = 2, high= 200 ,size= (2,9))
print(arr)
print('min',arr.min())
print('max',arr.max())
print('sum',arr.sum())
print('mean',arr.mean())
print('stdev',arr.std())

[[164 153  81 133  48 124 181  24 119]
 [108  75  14  79 170 190 124 114 158]]
min 14
max 190
sum 2059
mean 114.38888888888889
stdev 50.699702923618894
