In [2]:
import pandas as pd
import os
import requests
import numpy as np

#### Question 1. Pandas version (1 point)

In [3]:
pd.__version__

'2.2.2'

Download the data from url

In [4]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"

# Download and save the CSV file
response = requests.get(url)
with open('file.csv', 'wb') as file:
    file.write(response.content)

print("Download complete!")

Download complete!


#### Question 2.  Records count (1 point)

In [5]:
df = pd.read_csv('file.csv')
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [6]:
df.shape[0]

2160

#### Question 3. Laptop brands (1 point)

In [7]:
df.Brand.nunique()

27

#### Question 4. Missing values (1 point)

In [8]:
df.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

#### Question 5. Maximum final price (1 point)
What's the maximum final price of Dell notebooks in the dataset?



In [9]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [10]:
df[df['Brand']=='Dell']['Final Price'].max()

3936.0

#### Question 6. Median value of Screen (1 point)

In [11]:
# 1. Find the median value of Screen column in the dataset.
df['Screen'].median()

15.6

In [12]:
# 2. Next, calculate the most frequent value of the same Screen column.
df['Screen'].mode()[0]

15.6

In [13]:
# 3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
mode_value = df['Screen'].mode()[0]
df['Screen'] = df['Screen'].fillna(value= mode_value)
df['Screen'].isna().sum()

0

In [14]:
# 4. Now, calculate the median value of Screen once again.
df['Screen'].median()

15.6

#### Question 7. Sum of weights (1 point)

In [71]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [72]:
# 1. Select all the "Innjoo" laptops from the dataset.
Injoo_laptop = df['Laptop'].str.contains('Innjoo', case= False, na = False)
df[Injoo_laptop].head(n= 10)

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [73]:
#2. Select only columns RAM, Storage, Screen.
Injoo_laptop  = (df[df['Laptop']
                 .str.contains('Innjoo', case= False, na = False)]
                 .filter(['RAM','Storage','Screen']))
Injoo_laptop.head()

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1

In [74]:
# 3 Get the underlying NumPy array. Let's call it X.
X = Injoo_laptop.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [77]:
# 4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XT = X.T
print("Transpose \n",T,'\n')
XTX = XT@X
print("XTX \n",XTX)

Transpose 
 [[  8.    8.    4.    6.    6.    6. ]
 [256.  512.   64.   64.  128.  128. ]
 [ 15.6  15.6  14.1  14.1  14.1  14.1]] 

XTX 
 [[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [88]:
# 5. Compute the inverse of XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [89]:
# 6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100,1300,800,900,1000,1100])

In [95]:
#7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
weight = XTX_inv@X.T*y
weight

array([[ 289.28183831, -163.28302487, -325.17111146,  134.62818528,
          52.44041848,   57.68446033],
       [  -1.21170793,    3.83576374,    1.00713386,   -1.59921842,
          -0.76387432,   -0.84026175],
       [ -96.49448601,   35.07282588,  137.12712814,  -27.18972029,
          -1.53546111,   -1.68900722]])

In [96]:
# 8. What's the sum of all the elements of the result?
np.sum(weight)

91.29988062995567